#include <string>
#include <unordered_map>

static const enum AutonomousCmd { 
    RREVERSE 	, 
    LREVERSE	, 
    LCW 		, 
    RCW 		, 
    SPIN 		, 
    LCP 		, 
    RCP 		, 
    STOP 		, 
    PIVOTR 	, 
    PIVOTL 	, 
    FPIVOTR 	, 
    FPIVOTL 	, 
    VEERR 		, 
    VEERL 		, 
    FWD 		, 
    SLIGHTR 	, 
    SLIGHTL 	, 
    SPOOK 		, 
    GO 		,
};

static const std::unordered_map<std::string, AutonomousCmd> AUTOCMD_STRING_TO_ENUM = {
    "RREVERSE": AutonomousCmd.RREVERSE,
    "LREVERSE":	AutonomousCmd.LREVERSE,
    "LCW": AutonomousCmd.LCW,
    "RCW": AutonomousCmd.RCW,
    "SPIN" : AutonomousCmd.SPIN,
    "LCP": AutonomousCmd.LCP,
    "RCP": AutonomousCmd.RCP,
    "STOP": AutonomousCmd.STOP,
    "PIVOTR": AutonomousCmd.PIVOTR,
    "PIVOTL": AutonomousCmd.PIVOTL,
    "FPIVOTR": AutonomousCmd.FPIVOTR,
    "FPIVOTL": AutonomousCmd.FPIVOTL,
    "VEERR": AutonomousCmd.VEERR,
    "VEERL": AutonomousCmd.VEERL,
    "FWD": AutonomousCmd.FWD,
    "SLIGHTR": AutonomousCmd.SLIGHTR,
    "SLIGHTL": AutonomousCmd.SLIGHTL,
    "SPOOK": AutonomousCmd.SPOOK,
    "GO": AutonomousCmd.GO,
}