// Generated by gencpp from file eyes/Generic.msg
// DO NOT EDIT!


#ifndef EYES_MESSAGE_GENERIC_H
#define EYES_MESSAGE_GENERIC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace eyes
{
template <class ContainerAllocator>
struct Generic_
{
  typedef Generic_<ContainerAllocator> Type;

  Generic_()
    : identifier(0)
    , left_forward(false)
    , right_forward(false)
    , left_speed(0.0)
    , right_speed(0.0)
    , timed(false)
    , duration(0)  {
    }
  Generic_(const ContainerAllocator& _alloc)
    : identifier(0)
    , left_forward(false)
    , right_forward(false)
    , left_speed(0.0)
    , right_speed(0.0)
    , timed(false)
    , duration(0)  {
  (void)_alloc;
    }



   typedef uint8_t _identifier_type;
  _identifier_type identifier;

   typedef uint8_t _left_forward_type;
  _left_forward_type left_forward;

   typedef uint8_t _right_forward_type;
  _right_forward_type right_forward;

   typedef float _left_speed_type;
  _left_speed_type left_speed;

   typedef float _right_speed_type;
  _right_speed_type right_speed;

   typedef uint8_t _timed_type;
  _timed_type timed;

   typedef uint32_t _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::eyes::Generic_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::eyes::Generic_<ContainerAllocator> const> ConstPtr;

}; // struct Generic_

typedef ::eyes::Generic_<std::allocator<void> > Generic;

typedef boost::shared_ptr< ::eyes::Generic > GenericPtr;
typedef boost::shared_ptr< ::eyes::Generic const> GenericConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::eyes::Generic_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::eyes::Generic_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace eyes

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'eyes': ['/home/anonymous2/anon_auton_ws/src/eyes/msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::eyes::Generic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eyes::Generic_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eyes::Generic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eyes::Generic_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eyes::Generic_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eyes::Generic_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::eyes::Generic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "436f5f30261c38b114bc3f3bb4a0dea3";
  }

  static const char* value(const ::eyes::Generic_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x436f5f30261c38b1ULL;
  static const uint64_t static_value2 = 0x14bc3f3bb4a0dea3ULL;
};

template<class ContainerAllocator>
struct DataType< ::eyes::Generic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eyes/Generic";
  }

  static const char* value(const ::eyes::Generic_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::eyes::Generic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "char identifier\n"
"bool left_forward\n"
"bool right_forward\n"
"float32 left_speed\n"
"float32 right_speed\n"
"bool timed\n"
"uint32 duration\n"
;
  }

  static const char* value(const ::eyes::Generic_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::eyes::Generic_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.identifier);
      stream.next(m.left_forward);
      stream.next(m.right_forward);
      stream.next(m.left_speed);
      stream.next(m.right_speed);
      stream.next(m.timed);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Generic_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::eyes::Generic_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::eyes::Generic_<ContainerAllocator>& v)
  {
    s << indent << "identifier: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.identifier);
    s << indent << "left_forward: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_forward);
    s << indent << "right_forward: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_forward);
    s << indent << "left_speed: ";
    Printer<float>::stream(s, indent + "  ", v.left_speed);
    s << indent << "right_speed: ";
    Printer<float>::stream(s, indent + "  ", v.right_speed);
    s << indent << "timed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.timed);
    s << indent << "duration: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EYES_MESSAGE_GENERIC_H
