{
  "handwritten":
    {
      "left": "0Hf0.0f3.0",
      "right": "0Hf3.0f0.0",
      "fwd": "0Hf2.0f2.0",
      "ffwd": "0Hf3.0f3.0",
      "fwdl": "0Hf1.5f3.0",
      "fwdr": "0Hf3.0f1.5",
      "bwd": "0Hr2.0r2.0",
      "fbwd": "0Hr3.0r3.0",
      "bwdl": "0Hr1.5r3.0",
      "bwdr": "0Hr3.0r1.5",
      "pivotl": "0Hr2.5f2.5",
      "pivotr": "0Hf2.5r2.5",
      "stop": "0Hf0.0f0.0",
      "toggle": "0Htoggle",
    },
  "autonomous":
    {
      "RREVERSE": "ACD",
      "LREVERSE": "ACE",
      "LCW": "ACF",
      "RCW": "ACG",
      "SPIN": "ACH",
      "LCP": "BCI",
      "RCP": "BCJ",
      "STOP": "CAf0.0f0.0",
      "PIVOTR": "DAf2.5r2.5",
      "PIVOTL": "DAr2.5f2.5",
      "FPIVOTR": "DAf3.0r3.0",
      "FPIVOTL": "DAr3.0f3.0",
      "VEERR": "DAf3.0f1.5",
      "VEERL": "DAf1.5f3.0",
      "FWD": "DAf1.5f1.5",
      "BWD": "DAr1.5r1.5",
      "FFWD": "DAf2.0f2.0",
      "FBWD": "DAr2.0r2.0",
      "SLIGHTR": "DAf3.0f2.0",
      "SLIGHTL": "DAf2.0f3.0",
      "SPOOK": "EAf4.0f4.0",
      "GO": "FAf1.5f1.5",
    },
  "choreo":
    {
      "DANCE_C":
        [
          {
            "position": "1",
            "identifier": "c",
            "left_forward": "false",
            "right_forward": "false",
            "left_speed": "3.0",
            "right_speed": "3.0",
            "timed": "false",
            "duration": "10000",
          },
          {
            "position": "2",
            "identifier": "c",
            "left_forward": "false",
            "right_forward": "false",
            "left_speed": "0.0",
            "right_speed": "0.0",
            "timed": "true",
            "duration": "2",
          },
          {
            "position": "3",
            "identifier": "c",
            "left_forward": "false",
            "right_forward": "false",
            "left_speed": "3.0",
            "right_speed": "3.0",
            "timed": "false",
            "duration": "10000",
          },
          {
            "position": "4",
            "identifier": "c",
            "left_forward": "false",
            "right_forward": "false",
            "left_speed": "0.0",
            "right_speed": "0.0",
            "timed": "true",
            "duration": "2",
          },
          {
            "position": "-1",
            "identifier": "e",
            "left_forward": "true",
            "right_forward": "true",
            "left_speed": "0.0",
            "right_speed": "0.0",
            "timed": "true",
            "duration": "0",
          },
        ],
      "RREVERSE_C":
        [
          {
            "position": "1",
            "identifier": "c",
            "left_forward": "false",
            "right_forward": "false",
            "left_speed": "1.5",
            "right_speed": "1.5",
            "timed": "true",
            "duration": "3",
          },
          {
            "position": "2",
            "identifier": "c",
            "left_forward": "true",
            "right_forward": "false",
            "left_speed": "2.5",
            "right_speed": "2.5",
            "timed": "true",
            "duration": "5",
          },
          {
            "position": "3",
            "identifier": "c",
            "left_forward": "true",
            "right_forward": "false",
            "left_speed": "2.5",
            "right_speed": "2.5",
            "timed": "true",
            "duration": "5",
          },
          {
            "position": "-1",
            "identifier": "e",
            "left_forward": "true",
            "right_forward": "true",
            "left_speed": "0.0",
            "right_speed": "0.0",
            "timed": "true",
            "duration": "0",
          },
        ],
      "LREVERSE_C":
        [
          {
            "position": "1",
            "identifier": "c",
            "left_forward": "false",
            "right_forward": "false",
            "left_speed": "1.5",
            "right_speed": "1.5",
            "timed": "true",
            "duration": "3",
          },
          {
            "position": "2",
            "identifier": "c",
            "left_forward": "false",
            "right_forward": "true",
            "left_speed": "2.5",
            "right_speed": "2.5",
            "timed": "true",
            "duration": "5",
          },
          {
            "position": "3",
            "identifier": "c",
            "left_forward": "false",
            "right_forward": "true",
            "left_speed": "2.5",
            "right_speed": "2.5",
            "timed": "true",
            "duration": "5",
          },
          {
            "position": "-1",
            "identifier": "e",
            "left_forward": "true",
            "right_forward": "true",
            "left_speed": "0.0",
            "right_speed": "0.0",
            "timed": "true",
            "duration": "0",
          },
        ],
      "LCP_C":
        [
          {
            "position": "1",
            "identifier": "c",
            "left_forward": "false",
            "right_forward": "false",
            "left_speed": "1.5",
            "right_speed": "1.5",
            "timed": "true",
            "duration": "3",
          },
          {
            "position": "2",
            "identifier": "c",
            "left_forward": "false",
            "right_forward": "true",
            "left_speed": "2.5",
            "right_speed": "2.5",
            "timed": "true",
            "duration": "5",
          },
          {
            "position": "-1",
            "identifier": "e",
            "left_forward": "true",
            "right_forward": "true",
            "left_speed": "0.0",
            "right_speed": "0.0",
            "timed": "true",
            "duration": "0",
          },
        ],
      "RCP_C":
        [
          {
            "position": "1",
            "identifier": "c",
            "left_forward": "false",
            "right_forward": "false",
            "left_speed": "1.5",
            "right_speed": "1.5",
            "timed": "true",
            "duration": "3",
          },
          {
            "position": "2",
            "identifier": "c",
            "left_forward": "true",
            "right_forward": "false",
            "left_speed": "2.5",
            "right_speed": "2.5",
            "timed": "true",
            "duration": "5",
          },
          {
            "position": "-1",
            "identifier": "e",
            "left_forward": "true",
            "right_forward": "true",
            "left_speed": "0.0",
            "right_speed": "0.0",
            "timed": "true",
            "duration": "0",
          },
        ],
      "SPIN_C":
        [
          {
            "position": "1",
            "identifier": "c",
            "left_forward": "true",
            "right_forward": "false",
            "left_speed": "2.5",
            "right_speed": "2.5",
            "timed": "true",
            "duration": "5",
          },
          {
            "position": "2",
            "identifier": "c",
            "left_forward": "true",
            "right_forward": "false",
            "left_speed": "2.5",
            "right_speed": "2.5",
            "timed": "true",
            "duration": "5",
          },
          {
            "position": "-1",
            "identifier": "e",
            "left_forward": "true",
            "right_forward": "true",
            "left_speed": "0.0",
            "right_speed": "0.0",
            "timed": "true",
            "duration": "0",
          },
        ],
      "AUDIO_C":
        [
          {
            "position": "1",
            "identifier": "p",
            "left_forward": "true",
            "right_forward": "true",
            "left_speed": "0.0",
            "right_speed": "0.0",
            "timed": "true",
            "duration": "0",
          },
          {
            "position": "2",
            "identifier": "c",
            "left_forward": "true",
            "right_forward": "true",
            "left_speed": "0.0",
            "right_speed": "0.0",
            "timed": "true",
            "duration": "5",
          },
          {
            "position": "3",
            "identifier": "k",
            "left_forward": "true",
            "right_forward": "true",
            "left_speed": "0.0",
            "right_speed": "0.0",
            "timed": "true",
            "duration": "0",
          },
          {
            "position": "4",
            "identifier": "c",
            "left_forward": "true",
            "right_forward": "true",
            "left_speed": "2.0",
            "right_speed": "2.0",
            "timed": "false",
            "duration": "40000",
          },
          {
            "position": "5",
            "identifier": "t",
            "left_forward": "true",
            "right_forward": "true",
            "left_speed": "0.0",
            "right_speed": "0.0",
            "timed": "true",
            "duration": "0",
          },
          {
            "position": "6",
            "identifier": "c",
            "left_forward": "true",
            "right_forward": "true",
            "left_speed": "0.0",
            "right_speed": "0.0",
            "timed": "true",
            "duration": "5",
          },
          {
            "position": "7",
            "identifier": "c",
            "left_forward": "false",
            "right_forward": "false",
            "left_speed": "2.0",
            "right_speed": "2.0",
            "timed": "false",
            "duration": "40000",
          },
          {
            "position": "-1",
            "identifier": "e",
            "left_forward": "true",
            "right_forward": "true",
            "left_speed": "0.0",
            "right_speed": "0.0",
            "timed": "true",
            "duration": "0",
          },
        ],
    },
}
