{
  "camera":
    {
      "topBandWidth": 120,
      "sideBandWidth": 180,
      "imageWidth": 640,
      "imageHeight": 480,
      "brightnessThreshold": 125,
      "sidePercentThreshold": 0.20,
      "topPercentThreshold": 0.20,
      "numMiddlePixels": 100800,
      "test": 500,
    },
  "enable_statistics": true,
}
