camera:
  {
    "topBandWidth": 120,
    "sideBandWidth": 180,
    "imageWidth": 640,
    "imageHeight": 480,
    "brightnessThreshold": 175,
    "sidePercentThreshold": 0.50,
    "topPercentThreshold": 0.50,
    "numMiddlePixels": 100800,
    "test": 500,
  }
